# Site settings
name: Softelos
description: "Softelos is a Web Design and Development Agency located in Lynchburg (VA). We make beautiful, cutting edge, powerfull websites for clients all over the United States."
email: hello@softelos.com
baseurl: "" 
copyright: 2015
# Build settings
markdown: kramdown
excerpt_separator: <!--more-->


# S E R V I C E S

picWebsites: /assets/img/Web.png
iconWebsites: /assets/img/WebDesignIcon.png
textWebsites: "Websites"
textWebsitesShort: "Websites"

picCMS: /assets/img/cms.png
iconCMS: /assets/img/CMSIcon.png
textCMS: "CMS"
textCMSShort: "CMS"

picWebDev: /assets/img/WebDevelopment.png
iconWebDev: /assets/img/WebDevelopmentIcon.png
textWebDev: "Web Development"
textWebDevShort: "Web Development"

picResponsive: /assets/img/responsive.png
iconResponsive: /assets/img/ResponsiveIcon.png
textResponsive: "Mobile & Responsive"
textResponsiveShort: "Mobile & Responsive"

picECommerce: /assets/img/eCommerce.png
iconECommerce: /assets/img/eCommerceIcon.png
textECommerce: "Online Stores"
textECommerceShort: "Online Stores"

picSEO: /assets/img/SEO.png
iconSEO: /assets/img/SEOIcon.png
textSEO: "SEO"
textSEOShort: "SEO"

