# Site settings
url: http://www.softelos.com
name: Softelos LLC
titleHome: "Softelos • Web Design + Web Development + SEO • Lynchburg (VA)"
titleBase: " • Softelos • Web Design + Web Development + SEO • Lynchburg (VA)"
email: hello@softelos.com
baseurl: "" 
copyright: 2015
# Build settings
markdown: kramdown
excerpt_separator: <!--more-->

# S E R V I C E S

picWebsites: /assets/img/Web.png
iconWebsites: /assets/img/WebDesignIcon.png
textWebsites: "Web Design"
textWebsitesShort: "WebDesign"

picCMS: /assets/img/cms.png
iconCMS: /assets/img/CMSIcon.png
textCMS: "Content Management"
textCMSShort: "ContentManagement"

picWebDev: /assets/img/WebDevelopment.png
iconWebDev: /assets/img/WebDevelopmentIcon.png
textWebDev: "Web Development"
textWebDevShort: "WebDevelopment"

picResponsive: /assets/img/responsive.png
iconResponsive: /assets/img/ResponsiveIcon.png
textResponsive: "Mobile & Responsive"
textResponsiveShort: "MobileResponsive"

picECommerce: /assets/img/eCommerce.png
iconECommerce: /assets/img/eCommerceIcon.png
textECommerce: "Online Stores"
textECommerceShort: "OnlineStores"

picSEO: /assets/img/SEO.png
iconSEO: /assets/img/SEOIcon.png
textSEO: "SEO"
textSEOShort: "SEO"

gems:
  - jekyll-sitemap